### ISSUE TITLE
ERROR: 2021/08/24 17:00:46 coderefs.go:276: error retrieving repository: unauthorized, check your LaunchDarkly access token

### ISSUE THREAD

**Issue by sandipsubedi** [launchdarkly/find-code-references#18]
Hi there,

I am getting the following error even though I have already created `LD_ACCESS_TOKEN` which has `writer` `role` and added that as secrets on github. Not sure what I am missing. Any idea?

When I check here: https://app.launchdarkly.com/settings/authorization that token is `Never` used 🤔 

```
ERROR: 2021/08/24 17:00:46 coderefs.go:276: error retrieving repository: unauthorized, check your LaunchDarkly access token
```

This is what my config looks like:

```
on: push
name: Detect LaunchDarkly Feature Flag References
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This value must be set if the lookback configuration
          # option is not disabled for find-code-references.
          # Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
          fetch-depth: 11
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v11
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          githubToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: default

```

These are the prerequisites:

```
Prerequisites
To set up code references in LaunchDarkly, you must have the following prerequisites:

1. You must have an API access token with writer-level access or higher. Create an API access token in the Access Tokens page. To learn more, read API access tokens.

2. You must have a custom role that allows all actions on code references.

3. You must allow ld-find-code-refs to run in environment that has access to your source code.
```

I don't have a custom role, but from other documentation it seems like that is not necessary since I already have `writer` role.
