### ISSUE TITLE
Action Can't Execute Alias Command File

### ISSUE THREAD

**Issue by jwyza-pi** [launchdarkly/find-code-references#35]
I have the action setup and working, however I needed to be able to provide aliases for it. I setup a `.launchdarkly/coderefs.yaml` file with the following contents:

```yaml
aliases:
    - type: command
      command: .launchdarkly/flagAlias.sh
```

And a file in the same folder called `flagAlias.sh` with the following contents:

```sh
#! /bin/sh
read flagKey <&0; echo "[\"FeatureFlags.$flagKey\", \"'$flagKey'\", \"\\\"$flagKey\\\"\"]"
```

When I run this locally via the CLI in Ubuntu, `ld-find-code-refs --dryRun --projKey=default -t redactedkey -d . -r repo-name --debug`, it executes properly and appears to do what I expect.

When run in the github action, however, I get this error instead:

`ERROR: 2023/03/06 20:52:38 matcher.go:43: failed to generate aliases: filepattern '0': failed to execute alias command: fork/exec .launchdarkly/flagAlias.sh: permission denied`

So it seems that there is something funky with the docker image that is preventing the file from being executed.  

for reference, here's the github action file too:

```yaml
name: Find LaunchDarkly flag code references
on: push
# cancel in-flight workflow run if another push was triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.10.0
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: "default"
          debug: "true"
```
