### ISSUE TITLE
Cleaning up deleted branches

### ISSUE THREAD

**Issue by jazanne** [launchdarkly/find-code-references#51]
If you are running this action in a private repo, you will need to manually delete branches

Here is an example workflow:

```yaml
name: Delete code references branch
on: delete

jobs:
  branch-delete-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        if: ${{ github.event.ref_type == 'branch' }}
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: 'https://app.launchdarkly.com/api/v2/code-refs/repositories/${{ github.event.repository.name }}/branch-delete-tasks'
          method: POST
          customHeaders: '{"Authorization": "${{ secrets.LD_ACCESS_TOKEN }}"}'
          data: '["${{ github.event.ref }}"]'
          retry: 1
          retryWait: 1000
```
